version: '3.8'

services:
  mongo:
    image: mongo:7.0.17
    container_name: mongo
    command: ["mongod", "--replSet", "rs0", "--bind_ip_all"]
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
    driver: local


#    rs.initiate({
#    ...   _id: "rs0",
#    ...   members: [ { _id: 0, host: "localhost:27017" } ]
#    ... })
