version: '3.8'
name: mongo
services:
  mongodb-classic:
    image: mongo:7.0.17
    container_name: my-mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    ports:
      - "27018:27017"
